### ISSUE TITLE
Create method for simple Tokenizer

### ISSUE THREAD

**Issue by Nilanshrajput** [OpenMined/SyferText#105]
## Description
Create functionality in Tokenizer to do simple space based tokenization!
Its required at some places were it's essential strings don't split while tokenization, like in cases of sequence tagging, there is tag for each string defined we cannot let those strings modified otherwise for new token there might not any tag.

let user pass some argument if he needs simple tokenizer, like Tokenizer(simple = True)
## Additional Context
For ner tutorial.

**Comment by AlanAboudib** [comment]
This is a good point. Actually our current tokenizer is able to do that if you pass no rules (exceptions and affixes) with:

```
tokenizer = Tokenizer(exceptions = {}, prefixes = [], suffixes = [], infixes = [])
```

But I agree that although we have this functionality, there is no way we can apply it since the API does not allow us to do this.

However, this will be possible after the PyGrid integration PR. I implemented a method for the `Language` class called `set_tokenizer` and a method in the `Tokenizer` class called `load_rules()`.

Here is where you can check this out:

https://github.com/OpenMined/SyferText/blob/8aa390dc126b16085e2d5806cac9c82c357d2675/syfertext/tokenizer.py#L121

https://github.com/OpenMined/SyferText/blob/8aa390dc126b16085e2d5806cac9c82c357d2675/syfertext/language.py#L69

Is your issue urgent?

**Comment by bicycleman15** [comment]
That's a great idea. In my use case, I kind of need to clean medical texts and just split them about spaces. Passing through the complex tokenizer would cause bottlenecks in such cases where you dont care that much about tokenization, you are just content with basic space splitting.

**Comment by AlanAboudib** [comment]
I agree. It would be possible with PyGrid integration. Actually, it will be possible to build pipeline in a modular way like:

```
nlp = syfertext.create("syfertext_my_custom_model", owner = me)

simple_tokenizer = Tokenizer(exceptions = {}, prefixes = [], suffixes = [], infixes = [])

nlp.set_tokenizer(simple_tokenizer)

nlp.add_pipe(name = "grid://spacy/en_core_web_lg/ner")
nlp.add_pipe(name = "grid://syfertext/gsoc_medical/ner")
nlp.add_pipe(name = "grid://syfertext/skin_cancer/cancer_classifier")
```
