### ISSUE TITLE
Remove __len__ from SpanPointer and DocPointer

### ISSUE THREAD

**Issue by AlanAboudib** [OpenMined/SyferText#152]
## Description
Since I think it is still a security breach. 

Unless we figure out  really critical use cases that needs `__len__` on those classes, No need to leak any information about the dataset.

**Comment by AlanAboudib** [comment]
@bicycleman15 @Nilanshrajput @sachin-101 thoughts?

**Comment by bicycleman15** [comment]
I agree we should remove these methods, even though they don't reveal the entire text. We are still under development and don't know how these are going to play a role in a use case later down the line, so it's better not to have them at all for now for maximum privacy.
We added those features because we thought they could be useful but didn't think of something concrete. Let's not have them at all for now 👍

**Comment by AlanAboudib** [comment]
@bicycleman15 We are on the same page :+1: In order to enable testing, we have to introduce another mechanism that we should discuss Friday

**Comment by PyAgni** [comment]
@AlanAboudib I'm interested in taking this issue. Is this up for grabs?

**Comment by AlanAboudib** [comment]
Sure @PyAgni go ahead

**Comment by duggalsu** [comment]
Hi @AlanAboudib , I would like you take this up is still available

**Comment by Nilanshrajput** [comment]
go ahead @duggalsu (make your pr for syfertext_0.1.0 branch)

**Comment by Nilanshrajput** [comment]
done in #183
