### ISSUE TITLE
Update SimpleTokenizer to operate on DocPointer ?

### ISSUE THREAD

**Issue by sachin-101** [OpenMined/SyferText#69]
> remote (bool): If True, the pipe component will be sent to the remote worker
                where the Doc object resides. If False, the pipe will operate locally,
                either on a Doc object directly, or on a DocPointer returned by the previous
                component in the pipeline. Defaults to False.

SimpleTokenizer needs to be updated to operate on a DocPointer.

If this functionality is not required, we could at least go ahead and raise an `Object Not Collocated exception` rather than raising a `DocPointer Not Iterable exception`.

**Comment by bicycleman15** [comment]
There can be a case when we want to iterate on a remote doc when the data is not private. IMO we can leave it as `DocPointer Not Iterable` for now. 
Instead we can add a functionality to iterate on the doc pointer when we are given that the remote data is not private. 
I can work on adding this functionality or we can collab if you want ?

**Comment by bicycleman15** [comment]
What do you think @AlanAboudib ?

**Comment by AlanAboudib** [comment]
@sachin-101 @bicycleman15 

In the case where the doc is private, the `SimpleTagger` should be simply sent to the remote worker. This is faster. The `SimpleTagger` is not a private object, sending it to the remote worker is not a problem.

I envisaged `remote = False` in the case were you have a model, like a deep learning model for instance, that you cannot send to the remote worker, because it is private to the company and should not be revealed to the remote worker.

So `ObjectsNotCollocatedException` is a reasonable choice for me with a message like, "a local `SimpleTagger` cannot operate on  remote documents. please set `remote = True` when you add it to the pipeline"

**Comment by sachin-101** [comment]
Thanks for the clarification @AlanAboudib. I will add the exception and send a PR.

**Comment by AlanAboudib** [comment]
Any updates on this @sachin-101 ?

**Comment by sachin-101** [comment]
Yups. I added the exception in #49.

**Comment by AlanAboudib** [comment]
Thank you @sachin-101
